# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  networking.hostName = "nixvm";

  boot.loader.systemd-boot.enable = true;
  boot.loader.grub.enable = false;

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # {{{ Filesystems
  boot.initrd.luks.devices."nixvm-crypt".device = "/dev/disk/by-partlabel/nixvm-crypt";

  fileSystems =
  {
    "/" =
    {
      device  = "/dev/disk/by-label/nixvm";
      fsType  = "btrfs";
      options = [ "subvol=/root" ];
    };

    "/boot" =
    {
      device  = "/dev/disk/by-label/ESP";
      fsType  = "vfat";
      depends = [ "/" ];
    };

    "/.btrfs-root" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/" ];
    };

    "/nix" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/nix" ];
    };

    "/home" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/home" ];
    };

    "/.swap" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/swap" ];
    };

    "/.snapshots" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/snapshots" ];
    };

    "/.snapshots.externalhdd" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/snapshots.externalhdd" ];
    };

    "/var/cache" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/var-cache" ];
    };

    "/var/log" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/var-log" ];
    };

    "/var/tmp" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/var-tmp" ];
    };

    "/var/lib/libvirt/images" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" ];
      options = [ "subvol=/vms" ];
    };

    "/home/andy3153/games" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" "/home" ];
      options = [ "subvol=/games" ];
    };

    "/home/andy3153/torrents" =
    {
      device = "/dev/disk/by-label/nixvm";
      fsType = "btrfs";
      depends = [ "/" "/home" ];
      options = [ "subvol=/torrents" ];
    };
  };

  swapDevices = [ { device = "/.swap/swapfile"; } ];
  # }}}

}
